app = "movies-app-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "5000"
  # These will be overridden by fly secrets
  DATABASE_URL = ""
  JWT_SECRET = ""

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false  # Prevent auto-stopping due to inactivity
  auto_start_machines = true
  min_machines_running = 1    # Always keep at least one machine running
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"     # Give more time for the app to start
    interval = "15s"         # Check more frequently
    method = "GET"
    timeout = "10s"          # Increase timeout
    path = "/health"
    protocol = "http"
    tls_skip_verify = true   # Skip TLS verification for health checks

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # Increase memory to 1GB for better performance

[mounts]
  source = "movies_app_data"
  destination = "/app/uploads"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s" 